version: '3.9'

services:
  rabbit1:
    image: bitnami/rabbitmq:latest
    # build: .
    hostname: rabbitmq1
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
    ports:
      - 5672:5672
      - 15672:15672
    restart: always

  # rabbit2:
  #   # image: bitnami/rabbitmq:latest
  #   build: .
  #   hostname: rabbitmq2
  #   environment:
  #     - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
  #     - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
  #   ports:
  #     - 5673:5672
  #     - 15673:15672
  #   restart: always
